name: 🔧 Build MKDocs Image

on:
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.4.3
    with:
      image_name: ghcr.io/${{ github.repository }}/mkdocs
      dockerfile: images/docs-builder/Dockerfile
