name: Publish Docs

on:
  workflow_call:
    inputs:
      image:
        description: "Override the image to build mkdocs."
        required: false
        type: string
        default: "ghcr.io/hotosm/gh-workflows/mkdocs:main"
      keep_extra_files:
        description: "Only update modified files. Default false, to clean repo before push."
        required: false
        type: boolean
        default: false
      # TODO refactor to use single variable `include_artifacts`
      doxygen:
        description: "Include doxygen output uploaded to `artifact` key."
        required: false
        type: string
      # TODO refactor to use single variable `include_artifacts`
      openapi:
        description: "Include openapi output uploaded to `artifact` key."
        required: false
        type: string
      # TODO refactor to a single variable `include_artifacts`
      include_artifacts:
        description: "Include all uploaded artifacts from the workflow."
        required: false
        type: string

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish_docs:
    name: Publish GH Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Append Extra Files
        if: ${{ inputs.include_artifacts || inputs.doxygen || inputs.openapi }}
        uses: actions/download-artifact@v4
        with:
          # Default downloads all available artifacts to path
          path: docs/

      # TODO remove if zip is not required for upload
      # - name: Extract Doxygen Zip
      #   if: ${{ inputs.doxygen }}
      #   run: |
      #     tar -xvzf docs/doxygen.tar.gz
      #     rm docs/doxygen.tar.gz

      # - name: Extract Stories Zip
      #   if: ${{ inputs.stories }}
      #   run: |
      #     tar -xvzf docs/stories.tar.gz
      #     rm docs/stories.tar.gz

      - name: Publish
        run: |
          echo "Repo dir: $GITHUB_WORKSPACE"

          docker pull ${{ inputs.image }}

          docker run --volume $PWD:$PWD --workdir $PWD \
            --entrypoint=/bin/sh ${{ inputs.image }} \
            -c "\
              git config --global --add safe.directory $PWD \
              && mkdocs gh-deploy --force \
              ${{ inputs.keep_extra_files == 'true' && '--clean' || '--dirty' }}
            "
