name: Build OpenAPI JSON

on:
  workflow_call:
    inputs:
      image:
        description: "The image to build to OpenAPI JSON (dependencies included, i.e. FastAPI.)."
        required: true
        type: string
      example_env_file_path:
        description: "FastAPI must start with an environment set. Path to a .env with dummy vars."
        required: true
        type: string
      output_path:
        description: "If specified, the output dir is uploaded to the `artifact` key."
        required: false
        type: string
      container_user:
        description: "The user to run the container as. Defaults to root."
        required: false
        type: string
        default: root
      py_backend_app_context:
        description: "The context to import the FastAPI app from. Defaults to `app.main`."
        required: false
        type: string
        default: app.main
      py_backend_app_name:
        description: "The name of the FastAPI app. Defaults to `api`."
        required: false
        type: string
        default: api
      output_file_write_path:
        description: "The path to write the OpenAPI JSON file to. Defaults to `docs/openapi.json`."
        required: false
        type: string
        default: docs/openapi.json

jobs:
  build_openapi_json:
    name: Build OpenAPI JSON
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user ${{ inputs.container_user }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          EXAMPLE_DOTENV: ${{ inputs.example_env_file_path }}
        run: |
          echo "Checking if ${EXAMPLE_DOTENV} exists"
          if [ -f ${EXAMPLE_DOTENV} ]; then
            # Get a8m/envsubst (required for default vals syntax ${VAR:-default})
            echo "Downloading envsubst"
            curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
            if [ $? -ne 0 ]; then
                echo "Failed to download envsubst"
                exit 1
            fi
            chmod +x envsubst
            echo "Substituting variables from ${EXAMPLE_DOTENV} --> .env"
            ./envsubst < "${EXAMPLE_DOTENV}" > .env
          else
            echo "${EXAMPLE_DOTENV} not found, creating empty .env"
            touch .env
          fi

      - name: Build OpenAPI JSON
        env:
          DOTENV_FILE: .env
        run: |
          python - <<EOF
          """Get OpenAPI config from FastAPI and write to file."""

          import os
          import json
          from pathlib import Path

          from fastapi.openapi.utils import get_openapi
          from dotenv import load_dotenv

          load_dotenv(Path(os.getenv("DOTENV_FILE")))

          from ${{ inputs.py_backend_app_context }} import ${{ inputs.py_backend_app_name }}  # noqa: E402


          with open(Path("${{ inputs.output_file_write_path }}"), "w") as f:
              openapi = get_openapi(
                  title=api.title,
                  version=api.version,
                  openapi_version=api.openapi_version,
                  description=api.description,
                  routes=api.routes,
                  tags=api.openapi_tags,
                  servers=api.servers,
                  terms_of_service=api.terms_of_service,
                  contact=api.contact,
                  license_info=api.license_info,
              )
              json.dump(openapi, f, separators=(",", ":"))
          EOF

      - name: Upload Artifact Dir
        if: ${{ inputs.output_path }}
        uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.output_path }}
          name: openapi
