name: Terragrunt Apply

on:
  workflow_call:
    inputs:
      environment_name:
        description: "The Github environment name to get variables from. Default repository vars."
        required: false
        type: string
      environment_url:
        description: "URL that gets deployed with Github environment."
        required: false
        type: string
      load_env:
        description: "Load environment variables from GitHub Variables and Secret context."
        required: false
        type: boolean
        default: true
      working_dir:
        description: "Directory containing root terragrunt.hcl"
        required: false
        default: ${{ github.workspace }}
        type: string
      plan_file_name:
        description: "Enter Terragrunt Plan File name to run. If using s3 as artifact store pass s3 path here. Ex: naxa-ci-artifacts/some-prefix/plan"
        required: true
        type: string
      terraform_version:
        description: "Terraform Version"
        required: false
        default: "1.6.0"
        type: string
      opentofu_version:
        description: "Open Tofu Version"
        required: false
        default: "1.6.0"
        type: string
      terragrunt_version:
        description: "Terragrunt Version"
        required: false
        default: "0.54.12"
        type: string
      aws_use_oidc:
        description: "Prefer AWS OIDC auth"
        default: "true"
        type: string
      aws_region:
        description: "AWS Region"
        required: false
        default: "ap-south-1"
        type: string
      aws_access_key_id:
        description: "AWS_ACCESS_KEY_ID required if not aws_use_oidc"
        required: false
        type: string
      aws_secret_access_key:
        description: "AWS_SECRET_ACCESS_KEY required if not aws_use_oidc"
        required: false
        type: string
      use_gh_artifacts:
        description: "Use GitHub Artifacts to store plan file"
        required: false
        default: true
        type: boolean
      decrypt_plan_file:
        description: "Decrypt plan file uploaded to Github Artifacts or S3 with openssl. Use if encrypt_plan_file true on plan workflow. secrets.PLAN_FILE_ENCRYPTION_SECRET is required."
        required: false
        type: boolean
        default: false

env:
  AWS_REGION: ${{ inputs.aws_region }}
  tofu_version: ${{ inputs.opentofu_version }}
  tf_version: ${{ inputs.terraform_version }}
  tg_version: ${{ inputs.terragrunt_version }}
  working_dir: ${{ inputs.working_dir }}

jobs:
  apply:
    name: Apply Terragrunt Plan File
    runs-on: "ubuntu-latest"

    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.environment_url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Load Environment from GitHub variables & secrets.
        shell: bash
        if: ${{ inputs.load_env == true }}
        env:
          GIT_BRANCH: ${{ github.ref_name }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          # Random delimeter string for security
          delim=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

          # Parse JSON with multiline strings, using delimeter (Github specific)
          to_envs() { jq -r "to_entries[] | \"\(.key)<<$delim\n\(.value)\n$delim\n\""; }

          # Set vars to env for next step
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "TAG_OVERRIDE=${TAG_OVERRIDE}" >> $GITHUB_ENV

          # Set VARS_CONTEXT if not null
          if [ "${VARS_CONTEXT}" != "null" ]; then
            echo "${VARS_CONTEXT}" | to_envs >> $GITHUB_ENV
          fi

          # Set SECRETS_CONTEXT if not null
          if [ "${SECRETS_CONTEXT}" != "null" ]; then
            echo "${SECRETS_CONTEXT}" | to_envs >> $GITHUB_ENV
          fi

      - name: Setup AWS Credentials
        uses: hotosm/gh-workflows/.github/actions/configure_aws_credentials@configure_aws_credentials/1.0.0
        with:
          USE_OIDC_FOR_AWS: ${{inputs.aws_use_oidc }}
          AWS_CONFIG_FILE_PATH: ${{ github.workspace }}/.aws/credentials
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
          AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          AWS_REGION: ${{ inputs.AWS_REGION }}

      - name: Get Plan form S3
        if: ${{ inputs.use_gh_artifacts == false }}
        run: |
          aws s3 cp s3://${{ inputs.plan_file_name }}.plan.out ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out

      - name: Extract Artifact Run ID
        if: ${{ inputs.use_gh_artifacts == true }}
        id: extract_artifact_run_id
        shell: bash
        run: |
          result=$(echo "${{ inputs.plan_file_name }}" | awk -F'-' '{print $(NF-1)}')
          echo "ARTIFACT_RUN_ID=$result" >> $GITHUB_OUTPUT

      - name: Get Plan from GitHub Artifacts
        if: ${{ inputs.use_gh_artifacts == true }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.plan_file_name }}
          path: ${{ inputs.working_dir }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.extract_artifact_run_id.outputs.ARTIFACT_RUN_ID }}

      - name: Decrypt Plan file
        id: decrypt_plan_file
        if: ${{ inputs.decrypt_plan_file == true }}
        shell: bash
        run: |
          set -e
          if [[ -z "${{ secrets.PLAN_FILE_ENCRYPTION_SECRET }}" ]]
          then
            SECRET_ENC_KEY=UNSAFESTRINGUSEDUSECUSTOMSECRETKEY
          else
            SECRET_ENC_KEY=${{ secrets.PLAN_FILE_ENCRYPTION_SECRET }}
          fi
          echo "Encrypted Plan SHASUM: $(shasum ${{ inputs.working_dir }}${{ inputs.plan_file_name }}.plan.out)"
          cp ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out.enc
          openssl enc -d -aes-256-ctr -pbkdf2 -in ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out.enc -out ${{ inputs.working_dir }}/${{ inputs.plan_file_name }}.plan.out -pass pass:"${SECRET_ENC_KEY}"
          echo "Unencrypted Plan SHASUM: $(shasum ${{ inputs.working_dir }}${{ inputs.plan_file_name }}.plan.out)"

      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v2
        env:
          AWS_SHARED_CREDENTIALS_FILE: ${{ github.workspace }}/.aws/credentials
          INPUT_PRE_EXEC_1: export TERRAGRUNT_GIT_REPO_NAME=${{ github.event.repository.name }}
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: apply ${{ inputs.plan_file_name }}.plan.out
